title: Nicholas' personal webpage
email: me@nicholasfeltrin.com
description: >-
  My name is Nicholas, I'm a high school student with an interest to interesting things which peaks my interest, trust me they're intersting ;).
  This page was created as a safe place for me to express my interest, and hopefully I'll learn many things in doing so. Make yourself at home!

baseurl: ""
url: "https://www.nicholasfeltrin.com"

social:
  - title: Webpage
    url: https://www.nicholasfeltrin.com
  - title: Github
    url: https://github.com/NicholasFeltrin
