# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nicholas Feltrin
author:
  name: Nicholas Feltrin
  email: "me@nicholasfeltrin.com"
description: >- 
  Hey I'm Nicholas Feltrin a senior high school student interested in IT.

url: "https://nicholasfeltrin.com"

theme: minima
plugins:
  - jekyll-feed

index: _home/index.md
header_pages:
  - _home/tutorials.md
  - _home/donate.md
  - _home/info.md

collections: 
  home:
    output: true
    post: false
    premalink: /home/:path.html
  tutorials:
    output: true
    post: true
    permalink: /:categories/:title.html
  articles:
    output: true
    post: true
    permalink: /:categories/:title.html


defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
      categories: article

  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "post"
      categories: tutorial
    

minima:
  skin: classic
  social_links:
    github: NicholasFeltrin

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
